Repository DavidZamanian/Bachelor-thesis-blockchain-for-medical-records, pull requests merged in 2022-05, with the labels that each got.

#83 Update CID & Verify update
  client/src/Helpers/ehrService.js
Labels: enhancement, FRONTEND, High Priority, BACKEND

#92 Fixed some NewEntryScreen issues and Modals
  client/src/screens/Overview/EHROverviewScreen.js
  client/src/screens/Overview/styles.js
  client/src/screens/StaffScreens/NewEntryScreen/NewEntryScreen.js
Labels: enhancement, FRONTEND, Medium Priority

#98 Handle EHRs & Permissions
  client/src/Helpers/ehrService.js
  client/src/chainConnection/chainConnection.js
  client/src/placeholders/placeholderValues.js
  client/src/screens/LoginScreen/LoginScreen.js
  client/src/screens/Overview/EHROverviewScreen.js
  client/src/screens/StaffScreens/NewEntryScreen/NewEntryScreen.js
  client/src/screens/StaffScreens/PatientSearchScreen/PatientSearchScreen.js
Labels: enhancement, FRONTEND, High Priority

#101 Fixed misaligned divider and logo
  client/src/components/Footer.js
  client/src/screens/LoginScreen/LoginScreen.js
  client/src/screens/StaffScreens/NewEntryScreen/NewEntryScreen.js
Labels: enhancement, FRONTEND, Low Priority

#104 Firebase doctor's record key fix
  client/src/Helpers/ehrService.js
Labels: bug, FRONTEND, High Priority

#105 EHRService-refactoring
  client/src/Helpers/ehrService.js
  client/src/Helpers/firebaseService.js
  client/src/screens/Overview/EHROverviewScreen.js
  client/src/screens/StaffScreens/NewEntryScreen/NewEntryScreen.js
  client/src/screens/StaffScreens/PatientSearchScreen/PatientSearchScreen.js
Labels: Medium Priority, BACKEND

#106 Firebase setup instructions
  README.md
Labels: documentation, High Priority, FIREBASE

#108 RecordKeys now updates correctly in firebase when changing permissions
  .gitignore
  client/Crypto/crypt.js
  client/src/Helpers/ehrService.js
  client/src/Helpers/firebaseService.js
  client/src/chainConnection/chainConnection.js
  client/src/screens/Overview/EHROverviewScreen.js
  migrations/2_Block4EHR_migration.js
Labels: FRONTEND, High Priority, BACKEND, FIREBASE
