Repository DavidZamanian/Bachelor-thesis-blockchain-for-medical-records, pull requests merged in 2022-04, with the labels that each got.

#30 NewEntryScreen uploads to Web3Storage
  client/firebaseSetup.js
  client/package-lock.json
  client/package.json
  client/src/Helpers/Errors/FetchFileContentError.js
  client/src/Helpers/Errors/couldNotResolveCidError.js
  client/src/Helpers/Errors/createFileObjectError.js
  client/src/Helpers/Errors/downloadError.js
  client/src/Helpers/Errors/uploadFileError.js
  client/src/Helpers/ehrEntry.js
  client/src/Helpers/ehrService.js
  client/src/Helpers/fileService.js
  client/src/screens/Overview/EHROverviewScreen.js
  client/src/screens/StaffScreens/NewEntryScreen/NewEntryScreen.js
  client/src/styles.js
  client/yarn.lock
Labels: enhancement, FRONTEND

#50 Fixed PatientSearch bug
  client/src/Helpers/ehrService.js
  client/src/screens/StaffScreens/PatientSearchScreen/PatientSearchScreen.js
Labels: bug, FRONTEND, High Priority

#55 Smart contract and connection to the chain from client
  .github/workflows/node.js.yml
  README.md
  client/App.js
  client/contexts/ChainConnectionContext.js
  client/firebaseSetup.js
  client/package-lock.json
  client/package.json
  client/src/chainConnection/chainConnection.js
  client/src/chainConnection/chainConnectionFactory.js
  client/src/chainConnection/getWeb3.js
  client/src/screens/Overview/EHROverviewScreen.js
  client/yarn.lock
  contracts/Block4EHR.sol
  contracts/Migrations.sol
  migrations/1_initial_migration.js
  migrations/2_Block4EHR_migration.js
  package-lock.json
  package.json
  server/blockchainConnection/chainConnection.js
  test/tmp_contract_input/remix-testing.txt
  truffle-config.cjs
  truffle_test/package.json
  truffle_test/test/testBlock4EHR.js
Labels: enhancement, High Priority, BACKEND

#57 Pin Navbar to top
  client/src/components/Footer.js
  client/src/components/Header/Header.js
  client/src/screens/LoginScreen/LoginScreen.js
  client/src/screens/LoginScreen/styles.js
  client/src/screens/MiscScreens/styles.js
  client/src/screens/Overview/EHROverviewScreen.js
  client/src/screens/Overview/styles.js
  client/src/screens/StaffScreens/NewEntryScreen/NewEntryScreen.js
  client/src/screens/StaffScreens/PatientSearchScreen/styles.js
  client/src/styles.js
  client/src/theme.style.js
Labels: bug, FRONTEND, Low Priority

#56 Loading screen to hide blank page in EHROverview
  client/src/screens/Overview/EHROverviewScreen.js
  client/src/screens/Overview/styles.js
Labels: enhancement, FRONTEND, Medium Priority

#37 Switch to correct TextInput component
  client/src/screens/StaffScreens/PatientSearchScreen/PatientSearchScreen.js
Labels: bug, FRONTEND, Low Priority

#60 Frontend encrypts & decrypts EHRs
  client/Crypto/crypt.js
  client/src/Helpers/ehrService.js
  client/src/Helpers/fileService.js
  client/src/placeholders/placeholderValues.js
  test/testCrypto.js
Labels: enhancement, FRONTEND, High Priority

#58 Chain connection
  client/src/chainConnection/chainConnection.js
  client/src/chainConnection/chainConnectionError.js
  client/src/chainConnection/chainOperationDeniedError.js
  client/src/screens/Overview/EHROverviewScreen.js
  migrations/2_Block4EHR_migration.js
Labels: High Priority, BACKEND

#64 Refactored fetching of IPFS-files
  client/src/Helpers/ehrService.js
  client/src/Helpers/fileService.js
Labels: enhancement, FRONTEND, Medium Priority

#66 Regions in smart contract
  client/App.js
  client/src/chainConnection/chainConnection.js
  client/src/chainConnection/chainConnectionError.js
  client/src/chainConnection/chainConnectionFactory.js
  client/src/chainConnection/chainOperationDeniedError.js
  client/src/chainConnection/getWeb3.js
  client/src/screens/Overview/EHROverviewScreen.js
  contracts/Block4EHR.sol
  migrations/2_Block4EHR_migration.js
  truffle_test/test/testBlock4EHR.js
Labels: enhancement, High Priority, BACKEND

#71 Removed mention of BankID & improved bulletpoints
  client/src/screens/LoginScreen/LoginScreen.js
Labels: enhancement, question, FRONTEND, Medium Priority

#72 Project logo
  client/assets/PrimaryLogo.png
  client/assets/SecondaryLogo.png
  client/assets/TransparentLogo.png
  client/assets/WhiteLogo.png
  client/assets/favicon.png
  client/src/components/Footer.js
  client/src/components/Header/Header.js
  client/src/screens/MiscScreens/AboutScreen.js
  client/src/screens/Overview/EHROverviewScreen.js
  client/src/screens/Overview/styles.js
Labels: enhancement, question, FRONTEND, Medium Priority
